<a href="https://colab.research.google.com/github/KhushiChaudhary-cyber/Python_Assessment/blob/main/numpy_matrix_operations_advanced_py.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Program: NumPy Matrix Operations
# This program creates two matrices and performs:
# addition, subtraction, multiplication, and inverse operations

import numpy as np

# Create first matrix
matrix1 = np.array([
    [1, 2],
    [3, 4]
])

# Create second matrix
matrix2 = np.array([
    [5, 6],
    [7, 8]
])

# Display matrices
print("Matrix 1:\n", matrix1)
print("\nMatrix 2:\n", matrix2)

# Matrix Addition
addition = matrix1 + matrix2

# Matrix Subtraction
subtraction = matrix1 - matrix2

# Matrix Multiplication
multiplication = np.dot(matrix1, matrix2)

# Inverse of matrices
inverse_matrix1 = np.linalg.inv(matrix1)
inverse_matrix2 = np.linalg.inv(matrix2)

# Display results
print("\n--- Matrix Addition ---")
print(addition)

print("\n--- Matrix Subtraction ---")
print(subtraction)

print("\n--- Matrix Multiplication ---")
print(multiplication)

print("\n--- Inverse of Matrix 1 ---")
print(inverse_matrix1)

print("\n--- Inverse of Matrix 2 ---")
print(inverse_matrix2)

Matrix 1:
 [[1 2]
 [3 4]]

Matrix 2:
 [[5 6]
 [7 8]]

--- Matrix Addition ---
[[ 6  8]
 [10 12]]

--- Matrix Subtraction ---
[[-4 -4]
 [-4 -4]]

--- Matrix Multiplication ---
[[19 22]
 [43 50]]

--- Inverse of Matrix 1 ---
[[-2.   1. ]
 [ 1.5 -0.5]]

--- Inverse of Matrix 2 ---
[[-4.   3. ]
 [ 3.5 -2.5]]
